/**
 * OpenMaintenance API
 * API for managing maintenance tasks, equipments, and interventions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/api/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/api/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Openmaintenance);
  }
}(this, function(expect, Openmaintenance) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Openmaintenance.EquipmentApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EquipmentApi', function() {
    describe('equipmentsGet', function() {
      it('should call equipmentsGet successfully', function(done) {
        //uncomment below and update the code to test equipmentsGet
        //instance.equipmentsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('equipmentsIdDelete', function() {
      it('should call equipmentsIdDelete successfully', function(done) {
        //uncomment below and update the code to test equipmentsIdDelete
        //instance.equipmentsIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('equipmentsIdGet', function() {
      it('should call equipmentsIdGet successfully', function(done) {
        //uncomment below and update the code to test equipmentsIdGet
        //instance.equipmentsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('equipmentsIdPut', function() {
      it('should call equipmentsIdPut successfully', function(done) {
        //uncomment below and update the code to test equipmentsIdPut
        //instance.equipmentsIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('equipmentsPost', function() {
      it('should call equipmentsPost successfully', function(done) {
        //uncomment below and update the code to test equipmentsPost
        //instance.equipmentsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
