/**
 * OpenMaintenance API
 * API for managing maintenance tasks, equipments, and interventions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/api/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/api/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Openmaintenance);
  }
}(this, function(expect, Openmaintenance) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Openmaintenance.InterventionApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InterventionApi', function() {
    describe('interventionsGet', function() {
      it('should call interventionsGet successfully', function(done) {
        //uncomment below and update the code to test interventionsGet
        //instance.interventionsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('interventionsIdDelete', function() {
      it('should call interventionsIdDelete successfully', function(done) {
        //uncomment below and update the code to test interventionsIdDelete
        //instance.interventionsIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('interventionsIdGet', function() {
      it('should call interventionsIdGet successfully', function(done) {
        //uncomment below and update the code to test interventionsIdGet
        //instance.interventionsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('interventionsIdPut', function() {
      it('should call interventionsIdPut successfully', function(done) {
        //uncomment below and update the code to test interventionsIdPut
        //instance.interventionsIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('interventionsPost', function() {
      it('should call interventionsPost successfully', function(done) {
        //uncomment below and update the code to test interventionsPost
        //instance.interventionsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
