/**
 * OpenMaintenance API
 * API for managing maintenance tasks, equipments, and interventions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/api/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/api/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Openmaintenance);
  }
}(this, function(expect, Openmaintenance) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Openmaintenance.Task();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Task', function() {
    it('should create an instance of Task', function() {
      // uncomment below and update the code to test Task
      //var instance = new Openmaintenance.Task();
      //expect(instance).to.be.a(Openmaintenance.Task);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new Openmaintenance.Task();
      //expect(instance).to.be();
    });

    it('should have the property equipmentId (base name: "equipment_id")', function() {
      // uncomment below and update the code to test the property equipmentId
      //var instance = new Openmaintenance.Task();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Openmaintenance.Task();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new Openmaintenance.Task();
      //expect(instance).to.be();
    });

    it('should have the property hoursInterval (base name: "hours_interval")', function() {
      // uncomment below and update the code to test the property hoursInterval
      //var instance = new Openmaintenance.Task();
      //expect(instance).to.be();
    });

    it('should have the property monthsInterval (base name: "months_interval")', function() {
      // uncomment below and update the code to test the property monthsInterval
      //var instance = new Openmaintenance.Task();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new Openmaintenance.Task();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new Openmaintenance.Task();
      //expect(instance).to.be();
    });

  });

}));
