/**
 * OpenMaintenance API
 * API for managing maintenance tasks, equipments, and interventions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Equipment from '../model/Equipment';

/**
* Equipment service.
* @module api/api/EquipmentApi
* @version 1.0.0
*/
export default class EquipmentApi {

    /**
    * Constructs a new EquipmentApi. 
    * @alias module:api/api/EquipmentApi
    * @class
    * @param {module:api/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:api/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * List all equipments
     * Retrieve a list of all equipments
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:api/model/Equipment>} and HTTP response
     */
    equipmentsGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Equipment];
      return this.apiClient.callApi(
        '/equipments', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List all equipments
     * Retrieve a list of all equipments
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:api/model/Equipment>}
     */
    equipmentsGet() {
      return this.equipmentsGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete an equipment
     * Remove an equipment from the system
     * @param {Number} id ID of the equipment
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    equipmentsIdDeleteWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling equipmentsIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/equipments/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete an equipment
     * Remove an equipment from the system
     * @param {Number} id ID of the equipment
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    equipmentsIdDelete(id) {
      return this.equipmentsIdDeleteWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get equipment by ID
     * Retrieve a single equipment by its ID
     * @param {Number} id ID of the equipment
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:api/model/Equipment} and HTTP response
     */
    equipmentsIdGetWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling equipmentsIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Equipment;
      return this.apiClient.callApi(
        '/equipments/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get equipment by ID
     * Retrieve a single equipment by its ID
     * @param {Number} id ID of the equipment
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:api/model/Equipment}
     */
    equipmentsIdGet(id) {
      return this.equipmentsIdGetWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update an equipment
     * Update an existing equipment
     * @param {Number} id ID of the equipment
     * @param {module:api/model/Equipment} equipment 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:api/model/Equipment} and HTTP response
     */
    equipmentsIdPutWithHttpInfo(id, equipment) {
      let postBody = equipment;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling equipmentsIdPut");
      }
      // verify the required parameter 'equipment' is set
      if (equipment === undefined || equipment === null) {
        throw new Error("Missing the required parameter 'equipment' when calling equipmentsIdPut");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Equipment;
      return this.apiClient.callApi(
        '/equipments/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update an equipment
     * Update an existing equipment
     * @param {Number} id ID of the equipment
     * @param {module:api/model/Equipment} equipment 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:api/model/Equipment}
     */
    equipmentsIdPut(id, equipment) {
      return this.equipmentsIdPutWithHttpInfo(id, equipment)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create a new equipment
     * Add a new equipment to the system
     * @param {module:api/model/Equipment} equipment 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:api/model/Equipment} and HTTP response
     */
    equipmentsPostWithHttpInfo(equipment) {
      let postBody = equipment;
      // verify the required parameter 'equipment' is set
      if (equipment === undefined || equipment === null) {
        throw new Error("Missing the required parameter 'equipment' when calling equipmentsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Equipment;
      return this.apiClient.callApi(
        '/equipments', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create a new equipment
     * Add a new equipment to the system
     * @param {module:api/model/Equipment} equipment 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:api/model/Equipment}
     */
    equipmentsPost(equipment) {
      return this.equipmentsPostWithHttpInfo(equipment)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
