/**
 * OpenMaintenance API
 * API for managing maintenance tasks, equipments, and interventions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Intervention from '../model/Intervention';

/**
* Intervention service.
* @module api/api/InterventionApi
* @version 1.0.0
*/
export default class InterventionApi {

    /**
    * Constructs a new InterventionApi. 
    * @alias module:api/api/InterventionApi
    * @class
    * @param {module:api/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:api/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * List all interventions
     * Retrieve a list of all interventions
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:api/model/Intervention>} and HTTP response
     */
    interventionsGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Intervention];
      return this.apiClient.callApi(
        '/interventions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List all interventions
     * Retrieve a list of all interventions
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:api/model/Intervention>}
     */
    interventionsGet() {
      return this.interventionsGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete an intervention
     * Remove an intervention from the system
     * @param {Number} id ID of the intervention
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    interventionsIdDeleteWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling interventionsIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/interventions/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete an intervention
     * Remove an intervention from the system
     * @param {Number} id ID of the intervention
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    interventionsIdDelete(id) {
      return this.interventionsIdDeleteWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get intervention by ID
     * Retrieve a single intervention by its ID
     * @param {Number} id ID of the intervention
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:api/model/Intervention} and HTTP response
     */
    interventionsIdGetWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling interventionsIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Intervention;
      return this.apiClient.callApi(
        '/interventions/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get intervention by ID
     * Retrieve a single intervention by its ID
     * @param {Number} id ID of the intervention
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:api/model/Intervention}
     */
    interventionsIdGet(id) {
      return this.interventionsIdGetWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update an intervention
     * Update an existing intervention
     * @param {Number} id ID of the intervention
     * @param {module:api/model/Intervention} intervention 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:api/model/Intervention} and HTTP response
     */
    interventionsIdPutWithHttpInfo(id, intervention) {
      let postBody = intervention;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling interventionsIdPut");
      }
      // verify the required parameter 'intervention' is set
      if (intervention === undefined || intervention === null) {
        throw new Error("Missing the required parameter 'intervention' when calling interventionsIdPut");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Intervention;
      return this.apiClient.callApi(
        '/interventions/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update an intervention
     * Update an existing intervention
     * @param {Number} id ID of the intervention
     * @param {module:api/model/Intervention} intervention 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:api/model/Intervention}
     */
    interventionsIdPut(id, intervention) {
      return this.interventionsIdPutWithHttpInfo(id, intervention)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create a new intervention
     * Add a new intervention to the system
     * @param {module:api/model/Intervention} intervention 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:api/model/Intervention} and HTTP response
     */
    interventionsPostWithHttpInfo(intervention) {
      let postBody = intervention;
      // verify the required parameter 'intervention' is set
      if (intervention === undefined || intervention === null) {
        throw new Error("Missing the required parameter 'intervention' when calling interventionsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Intervention;
      return this.apiClient.callApi(
        '/interventions', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create a new intervention
     * Add a new intervention to the system
     * @param {module:api/model/Intervention} intervention 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:api/model/Intervention}
     */
    interventionsPost(intervention) {
      return this.interventionsPostWithHttpInfo(intervention)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
