/**
 * OpenMaintenance API
 * API for managing maintenance tasks, equipments, and interventions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Task from '../model/Task';

/**
* Task service.
* @module api/api/TaskApi
* @version 1.0.0
*/
export default class TaskApi {

    /**
    * Constructs a new TaskApi. 
    * @alias module:api/api/TaskApi
    * @class
    * @param {module:api/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:api/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * List all tasks
     * Retrieve a list of all tasks
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:api/model/Task>} and HTTP response
     */
    tasksGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Task];
      return this.apiClient.callApi(
        '/tasks', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List all tasks
     * Retrieve a list of all tasks
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:api/model/Task>}
     */
    tasksGet() {
      return this.tasksGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete a task
     * Remove a task from the system
     * @param {Number} id ID of the task
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    tasksIdDeleteWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling tasksIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/tasks/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete a task
     * Remove a task from the system
     * @param {Number} id ID of the task
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    tasksIdDelete(id) {
      return this.tasksIdDeleteWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get task by ID
     * Retrieve a single task by its ID
     * @param {Number} id ID of the task
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:api/model/Task} and HTTP response
     */
    tasksIdGetWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling tasksIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Task;
      return this.apiClient.callApi(
        '/tasks/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get task by ID
     * Retrieve a single task by its ID
     * @param {Number} id ID of the task
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:api/model/Task}
     */
    tasksIdGet(id) {
      return this.tasksIdGetWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update a task
     * Update an existing task
     * @param {Number} id ID of the task
     * @param {module:api/model/Task} task 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:api/model/Task} and HTTP response
     */
    tasksIdPutWithHttpInfo(id, task) {
      let postBody = task;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling tasksIdPut");
      }
      // verify the required parameter 'task' is set
      if (task === undefined || task === null) {
        throw new Error("Missing the required parameter 'task' when calling tasksIdPut");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Task;
      return this.apiClient.callApi(
        '/tasks/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update a task
     * Update an existing task
     * @param {Number} id ID of the task
     * @param {module:api/model/Task} task 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:api/model/Task}
     */
    tasksIdPut(id, task) {
      return this.tasksIdPutWithHttpInfo(id, task)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create a new task
     * Add a new task to the system
     * @param {module:api/model/Task} task 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:api/model/Task} and HTTP response
     */
    tasksPostWithHttpInfo(task) {
      let postBody = task;
      // verify the required parameter 'task' is set
      if (task === undefined || task === null) {
        throw new Error("Missing the required parameter 'task' when calling tasksPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Task;
      return this.apiClient.callApi(
        '/tasks', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create a new task
     * Add a new task to the system
     * @param {module:api/model/Task} task 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:api/model/Task}
     */
    tasksPost(task) {
      return this.tasksPostWithHttpInfo(task)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
