/**
 * OpenMaintenance API
 * API for managing maintenance tasks, equipments, and interventions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Intervention model module.
 * @module api/model/Intervention
 * @version 1.0.0
 */
class Intervention {
    /**
     * Constructs a new <code>Intervention</code>.
     * @alias module:api/model/Intervention
     */
    constructor() { 
        
        Intervention.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Intervention</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:api/model/Intervention} obj Optional instance to populate.
     * @return {module:api/model/Intervention} The populated <code>Intervention</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Intervention();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('task_id')) {
                obj['task_id'] = ApiClient.convertToType(data['task_id'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], 'String');
            }
            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Intervention</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Intervention</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['location'] && !(typeof data['location'] === 'string' || data['location'] instanceof String)) {
            throw new Error("Expected the field `location` to be a primitive type in the JSON string but got " + data['location']);
        }
        // ensure the json data is a string
        if (data['comments'] && !(typeof data['comments'] === 'string' || data['comments'] instanceof String)) {
            throw new Error("Expected the field `comments` to be a primitive type in the JSON string but got " + data['comments']);
        }

        return true;
    }


}



/**
 * Unique identifier for the intervention
 * @member {Number} id
 */
Intervention.prototype['id'] = undefined;

/**
 * ID of the associated task
 * @member {Number} task_id
 */
Intervention.prototype['task_id'] = undefined;

/**
 * Date of the intervention
 * @member {Date} date
 */
Intervention.prototype['date'] = undefined;

/**
 * Location where the intervention was performed
 * @member {String} location
 */
Intervention.prototype['location'] = undefined;

/**
 * Additional comments about the intervention
 * @member {String} comments
 */
Intervention.prototype['comments'] = undefined;

/**
 * When the intervention was created
 * @member {Date} created_at
 */
Intervention.prototype['created_at'] = undefined;

/**
 * When the intervention was last updated
 * @member {Date} updated_at
 */
Intervention.prototype['updated_at'] = undefined;






export default Intervention;

