/**
 * OpenMaintenance API
 * API for managing maintenance tasks, equipments, and interventions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Task model module.
 * @module api/model/Task
 * @version 1.0.0
 */
class Task {
    /**
     * Constructs a new <code>Task</code>.
     * @alias module:api/model/Task
     */
    constructor() { 
        
        Task.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Task</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:api/model/Task} obj Optional instance to populate.
     * @return {module:api/model/Task} The populated <code>Task</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Task();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('equipment_id')) {
                obj['equipment_id'] = ApiClient.convertToType(data['equipment_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('hours_interval')) {
                obj['hours_interval'] = ApiClient.convertToType(data['hours_interval'], 'Number');
            }
            if (data.hasOwnProperty('months_interval')) {
                obj['months_interval'] = ApiClient.convertToType(data['months_interval'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Task</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Task</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}



/**
 * Unique identifier for the task
 * @member {Number} id
 */
Task.prototype['id'] = undefined;

/**
 * ID of the associated equipment
 * @member {Number} equipment_id
 */
Task.prototype['equipment_id'] = undefined;

/**
 * Name of the task
 * @member {String} name
 */
Task.prototype['name'] = undefined;

/**
 * Detailed description of the task
 * @member {String} description
 */
Task.prototype['description'] = undefined;

/**
 * Interval in hours for the task
 * @member {Number} hours_interval
 */
Task.prototype['hours_interval'] = undefined;

/**
 * Interval in months for the task
 * @member {Number} months_interval
 */
Task.prototype['months_interval'] = undefined;

/**
 * When the task was created
 * @member {Date} created_at
 */
Task.prototype['created_at'] = undefined;

/**
 * When the task was last updated
 * @member {Date} updated_at
 */
Task.prototype['updated_at'] = undefined;






export default Task;

