/**
 * OpenMaintenance API
 * API for managing maintenance tasks, equipments, and interventions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Equipment from './model/Equipment';
import Intervention from './model/Intervention';
import Task from './model/Task';
import EquipmentApi from './api/EquipmentApi';
import InterventionApi from './api/InterventionApi';
import TaskApi from './api/TaskApi';


/**
* API for managing maintenance tasks, equipments, and interventions.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Openmaintenance = require('api/index'); // See note below*.
* var xxxSvc = new Openmaintenance.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Openmaintenance.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['api/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Openmaintenance.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Openmaintenance.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module api/index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:api/ApiClient}
     */
    ApiClient,

    /**
     * The Equipment model constructor.
     * @property {module:api/model/Equipment}
     */
    Equipment,

    /**
     * The Intervention model constructor.
     * @property {module:api/model/Intervention}
     */
    Intervention,

    /**
     * The Task model constructor.
     * @property {module:api/model/Task}
     */
    Task,

    /**
    * The EquipmentApi service constructor.
    * @property {module:api/api/EquipmentApi}
    */
    EquipmentApi,

    /**
    * The InterventionApi service constructor.
    * @property {module:api/api/InterventionApi}
    */
    InterventionApi,

    /**
    * The TaskApi service constructor.
    * @property {module:api/api/TaskApi}
    */
    TaskApi
};
